"""automation settings, job retry columns and indexes

Revision ID: 0002_automation_and_retry
Revises: 0002_provider_registry
Create Date: 2026-06-05

Mirrors app/database/models.py changes for automation/queue/drive-watcher:
- transcription_jobs gains next_retry_at + last_error_code and two indexes;
- a new user_automation_settings table for per-user auto-poll + guardrails.
Hand-written (not autogenerated) so it works without a live database.
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0002_automation_and_retry"
down_revision: Union[str, None] = "0002_provider_registry"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- transcription_jobs: retry scheduling columns + indexes --------------
    op.add_column(
        "transcription_jobs",
        sa.Column("last_error_code", sa.Text(), nullable=True),
    )
    op.add_column(
        "transcription_jobs",
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(
        "ix_transcription_jobs_status_next_retry",
        "transcription_jobs",
        ["status", "next_retry_at"],
    )
    op.create_index(
        "ix_transcription_jobs_user_created",
        "transcription_jobs",
        ["user_id", "created_at"],
    )

    # --- user_automation_settings -------------------------------------------
    op.create_table(
        "user_automation_settings",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "auto_poll_enabled", sa.Boolean(), nullable=False,
            server_default=sa.text("false"),
        ),
        sa.Column(
            "poll_interval_seconds", sa.Integer(), nullable=False,
            server_default=sa.text("300"),
        ),
        sa.Column(
            "max_files_per_poll", sa.Integer(), nullable=False,
            server_default=sa.text("5"),
        ),
        sa.Column("last_poll_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_code", sa.Text(), nullable=True),
        sa.Column("last_error_message", sa.Text(), nullable=True),
        sa.Column("daily_jobs_limit", sa.Integer(), nullable=True),
        sa.Column("max_file_size_mb", sa.Integer(), nullable=True),
        sa.Column("monthly_cloud_minutes_limit", sa.Integer(), nullable=True),
        sa.Column("max_file_duration_minutes", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
    )
    op.create_index(
        "ix_user_automation_settings_user_id",
        "user_automation_settings",
        ["user_id"],
        unique=True,
    )
    op.create_index(
        "ix_user_automation_enabled_polled",
        "user_automation_settings",
        ["auto_poll_enabled", "last_poll_at"],
    )


def downgrade() -> None:
    op.drop_index("ix_user_automation_enabled_polled", table_name="user_automation_settings")
    op.drop_index("ix_user_automation_settings_user_id", table_name="user_automation_settings")
    op.drop_table("user_automation_settings")
    op.drop_index("ix_transcription_jobs_user_created", table_name="transcription_jobs")
    op.drop_index(
        "ix_transcription_jobs_status_next_retry", table_name="transcription_jobs"
    )
    op.drop_column("transcription_jobs", "next_retry_at")
    op.drop_column("transcription_jobs", "last_error_code")
