"""provider registry tables (models tab)

Revision ID: 0002_provider_registry
Revises: 0001_initial
Create Date: 2026-06-05

Adds ``provider_credentials`` (per-user, per-provider encrypted API keys) and
``user_model_settings`` (per-user provider/model selection + fallback). Existing
``deepgram_credentials`` rows are copied into ``provider_credentials`` with
``provider='deepgram'`` so keys saved before the Models tab keep working. The
legacy table is intentionally NOT dropped (backward-compatible reads).

Hand-written (not autogenerated); index/constraint names match what
``Base.metadata.create_all`` produces.
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0002_provider_registry"
down_revision: Union[str, None] = "0001_initial"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "provider_credentials",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("encrypted_api_key", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.UniqueConstraint("user_id", "provider", name="uq_provider_credentials_user_provider"),
    )
    op.create_index(
        "ix_provider_credentials_user_id", "provider_credentials", ["user_id"]
    )

    op.create_table(
        "user_model_settings",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("primary_provider", sa.Text(), nullable=False, server_default=sa.text("'deepgram'")),
        sa.Column("primary_model", sa.Text(), nullable=False, server_default=sa.text("'nova-3'")),
        sa.Column("fallback_enabled", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("fallback_provider", sa.Text(), nullable=True),
        sa.Column("fallback_model", sa.Text(), nullable=True),
        sa.Column("local_engine", sa.Text(), nullable=True),
        sa.Column("local_model", sa.Text(), nullable=True),
        sa.Column("local_quantization", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
    )
    op.create_index(
        "ix_user_model_settings_user_id", "user_model_settings", ["user_id"], unique=True
    )

    # Backfill: carry existing per-user Deepgram keys into the new table so the
    # Models tab and worker see them without the user re-entering anything.
    op.execute(
        sa.text(
            """
            INSERT INTO provider_credentials
                (user_id, provider, encrypted_api_key, created_at, updated_at)
            SELECT user_id, 'deepgram', encrypted_api_key, created_at, updated_at
            FROM deepgram_credentials
            ON CONFLICT (user_id, provider) DO NOTHING
            """
        )
    )


def downgrade() -> None:
    op.drop_index("ix_user_model_settings_user_id", table_name="user_model_settings")
    op.drop_table("user_model_settings")
    op.drop_index("ix_provider_credentials_user_id", table_name="provider_credentials")
    op.drop_table("provider_credentials")
