"""add per-user chrome extension upload tokens

Revision ID: 0002_extension_tokens
Revises: 0002_transcript_fts
Create Date: 2026-06-06

Adds ``user_extension_tokens``: one row per (user, token), allowing each user
to mint and revoke as many extension tokens as they want. The real token
crosses the network only at creation time; we persist only its salted hash
plus a short prefix used to render a masked list in the UI.

Hand-written (not autogenerated) so it works without a live database; index
and constraint names match what ``Base.metadata.create_all`` produces.
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002_extension_tokens"
down_revision: Union[str, None] = "0002_transcript_fts"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "user_extension_tokens",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("token_prefix", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
    )
    op.create_index(
        "ix_user_extension_tokens_user", "user_extension_tokens", ["user_id"]
    )
    op.create_index(
        "ix_user_extension_tokens_prefix", "user_extension_tokens", ["token_prefix"]
    )


def downgrade() -> None:
    op.drop_index("ix_user_extension_tokens_prefix", table_name="user_extension_tokens")
    op.drop_index("ix_user_extension_tokens_user", table_name="user_extension_tokens")
    op.drop_table("user_extension_tokens")
